orders_plugin = [
    "session_storage",
    "pony_db",
    "app",
    "jwt_token",
    "flask_app",
    "redis",
    "auth",
]

[plugins.redis]
host = '@format {env[AUTH_REDIS_HOST]}'
port = '@format {env[AUTH_REDIS_PORT]}'
db = '@format {env[AUTH_REDIS_DB]}'

[plugins.jwt_token]
secret_key = '@format {env[AUTH_JWT_SECRET_KEY]}'
refresh_token_expires = '@format {env[AUTH_JWT_REFRESH_TOKEN_EXPIRES]}'
access_token_expires = '@format {env[AUTH_JWT_ACCESS_TOKEN_EXPIRES]}'

[plugins.pony_db]
debug = 'False'
user = '@format {env[AUTH_POSTGRES_USER]}'
password = '@format {env[AUTH_POSTGRES_PASS]}'
port = '@format {env[AUTH_POSTGRES_PORT]}'
host = '@format {env[AUTH_POSTGRES_HOST]}'
database = '@format {env[AUTH_POSTGRES_DB]}'

[plugins.auth]
fingerprint_secret_key = '@format {env[AUTH_APP_FINGERPRINT_SECRET_KEY]}'

[plugins.session_storage]
type_storage = '@format {env[AUTH_SESSION_STORAGE_TYPE_STORAGE]}'