orders_plugin = [
    "pony_db",
    "app",
    "jwt_token",
    "flask_app",
    "redis",
]

[plugins.redis]
host = '@format {env[AUTH_REDIS_HOST]}'
port = '@format {env[AUTH_REDIS_PORT]}'
db = '@format {env[AUTH_REDIS_DB]}'

[plugins.jwt_token]
jwt_secret_key = '@format {env[AUTH_JWT_SECRET_KEY]}'
jwt_refresh_token_expires = '@format {env[AUTH_JWT_REFRESH_TOKEN_EXPIRES]}'
jwt_access_token_expires = '@format {env[AUTH_JWT_ACCESS_TOKEN_EXPIRES]}'

[plugins.pony_db]
debug = 'False'
user = '@format {env[AUTH_POSTGRES_USER]}'
password = '@format {env[AUTH_POSTGRES_PASS]}'
port = '@format {env[AUTH_POSTGRES_PORT]}'
host = '@format {env[AUTH_POSTGRES_HOST]}'
database = '@format {env[AUTH_POSTGRES_DB]}'