###

GET http://127.0.0.1:8080/history_login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMWFmZDE3ZmQtYjZmNS00YTkzLTgxOTQtMTZkMjJiMmI1YmU3IiwiZmluZ2VycHJpbnQiOiJiJ2dBQUFBQUJraWJObnRqaENtUmZGc3FWdDVwS2hIc3N1aEMyMXpJUjI3bVpQRUhadk5qeGdZeHJtZ1M3SEx4WnhwZDJiLWtKN0xBaFhORWRna2NLTDBvZC1ZYlVfci1XYlZfZk9wTmlrcVQtWm1oZklaQ1VPTUpPN0hHX1lnVEQ1cU9RTC1aNDcxNnN0MXF5cHNiWEVWdnpnM1JidUQ0TXZCUT09JyIsImV4cCI6MTY4Njc0NjA3OX0.jQI2CD_-WMuCtYD-JkM2sxJssytUi3uAmd2Gy5P45N8

###


# curl --location --request POST 'http://127.0.0.1:8080/login?login=anton&password=qwerty123'
POST http://127.0.0.1:8080/login?login=anton&password=qwerty123

###


